name: Successful Pipeline

on:
  workflow_dispatch:

jobs:
  autotests:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "Pipeline started"

      - name: Run tests
        run: echo "All tests passed"

      - name: Finish
        run: echo "Pipeline finished"
